package com.colofabrix.scala.figlet4s

import com.colofabrix.scala.figlet4s.figfont._
import scala.io.Source
import cats.data.Validated._

object Figlet4s extends App {
  val fonts = List(
    "1row.flf",
    "3-d.flf",
    "3x5.flf",
    "4max.flf",
    "5lineoblique.flf",
    "B1FF.flf",
    "acrobatic.flf",
    "alligator.flf",
    "alligator2.flf",
    // "alligator3.flf",
    "alpha.flf",
    "alphabet.flf",
    "amc3line.flf",
    "amc3liv1.flf",
    "amcaaa01.flf",
    "amcneko.flf",
    "amcrazo2.flf",
    "amcrazor.flf",
    "amcslash.flf",
    "amcslder.flf",
    "amcthin.flf",
    "amctubes.flf",
    "amcun1.flf",
    "arrows.flf",
    "avatar.flf",
    "banner.flf",
    "banner3-D.flf",
    "banner3.flf",
    "banner4.flf",
    "barbwire.flf",
    "basic.flf",
    "bell.flf",
    "benjamin.flf",
    "big.flf",
    "bigchief.flf",
    "bigfig.flf",
    "binary.flf",
    "block.flf",
    "bolger.flf",
    "bright.flf",
    "broadway.flf",
    "bubble.flf",
    "bulbhead.flf",
    "calgphy2.flf",
    "caligraphy.flf",
    "catwalk.flf",
    "chunky.flf",
    "coinstak.flf",
    "colossal.flf",
    "computer.flf",
    "contessa.flf",
    "contrast.flf",
    "cosmic.flf",
    "cosmike.flf",
    "crawford.flf",
    "cricket.flf",
    "cyberlarge.flf",
    "cybermedium.flf",
    "cybersmall.flf",
    "decimal.flf",
    "diamond.flf",
    "digital.flf",
    "doh.flf",
    "doom.flf",
    "dosrebel.flf",
    "dotmatrix.flf",
    // "double.flf",
    "drpepper.flf",
    "eftichess.flf",
    "eftifont.flf",
    "eftipiti.flf",
    "eftirobot.flf",
    "eftitalic.flf",
    "eftiwall.flf",
    "eftiwater.flf",
    "epic.flf",
    "fender.flf",
    "fourtops.flf",
    "fraktur.flf",
    "fuzzy.flf",
    "goofy.flf",
    "gothic.flf",
    "gradient.flf",
    "graffiti.flf",
    "greek.flf",
    "henry3d.flf",
    "hex.flf",
    "hollywood.flf",
    "invita.flf",
    "isometric1.flf",
    "isometric2.flf",
    "isometric3.flf",
    "isometric4.flf",
    "italic.flf",
    "ivrit.flf",
    "jacky.flf",
    "jazmine.flf",
    "jerusalem.flf",
    "katakana.flf",
    "kban.flf",
    "keyboard.flf",
    // "konto.flf",
    // "kontoslant.flf",
    "larry3d.flf",
    "lcd.flf",
    "lean.flf",
    "letters.flf",
    "linux.flf",
    "lockergnome.flf",
    "madrid.flf",
    "marquee.flf",
    "maxfour.flf",
    "mike.flf",
    "mini.flf",
    "mirror.flf",
    "mnemonic.flf",
    "morse.flf",
    "moscow.flf",
    "nancyj-fancy.flf",
    "nancyj-improved.flf",
    "nancyj-underlined.flf",
    "nancyj.flf",
    "nipples.flf",
    "nscript.flf",
    "ntgreek.flf",
    "o8.flf",
    "octal.flf",
    "ogre.flf",
    "oldbanner.flf",
    "os2.flf",
    "pawp.flf",
    "peaks.flf",
    "peaksslant.flf",
    "pebbles.flf",
    "pepper.flf",
    "poison.flf",
    "puffy.flf",
    // "pyramid.flf",
    "rectangles.flf",
    "redphoenix.flf",
    "relief.flf",
    "relief2.flf",
    "reverse.flf",
    "roman.flf",
    "rot13.flf",
    "rounded.flf",
    "rowancap.flf",
    "rozzo.flf",
    "runic.flf",
    "s-relief.flf",
    "santaclara.flf",
    "sblood.flf",
    "script.flf",
    "serifcap.flf",
    "shadow.flf",
    "shimrod.flf",
    "short.flf",
    "slant.flf",
    "slide.flf",
    "slscript.flf",
    "small.flf",
    "smisome1.flf",
    "smkeyboard.flf",
    "smpoison.flf",
    "smscript.flf",
    "smshadow.flf",
    "smslant.flf",
    "smtengwar.flf",
    "speed.flf",
    "stacey.flf",
    "stampate.flf",
    "stampatello.flf",
    "standard.flf",
    "starwars.flf",
    "stellar.flf",
    "stop.flf",
    "straight.flf",
    "sub-zero.flf",
    "tanja.flf",
    "tengwar.flf",
    "term.flf",
    "thick.flf",
    "thin.flf",
    "threepoint.flf",
    "ticks.flf",
    "ticksslant.flf",
    "tiles.flf",
    "tinker-toy.flf",
    "tombstone.flf",
    "trek.flf",
    "tsalagi.flf",
    "tubular.flf",
    "twopoint.flf",
    "univers.flf",
    "usaflag.flf",
    "weird.flf",
    "whimsy.flf",
  )

  import scala.io.Codec
  // val decoder = Codec.UTF8.decoder.onMalformedInput(java.nio.charset.CodingErrorAction.CodingErrorAction.IGNORE)
  val decoder = Codec.ISO8859

  // val lines = Source.fromResource(s"fonts/jacky.flf")(decoder).getLines().toVector
  // val fontV = FIGfont(lines)
  // fontV.fold(println(_), printFont("Claire")(_))

  for (font <- fonts) {
    val lines = Source.fromResource(s"fonts/$font")(decoder).getLines().toVector
    val fontV = FIGfont(lines)
    fontV match {
      case Invalid(e) =>
        println(s"Font: $font")
        pprint.pprintln(e)
      case Valid(font) =>
        printFont("ABC abc 012")(font)
    }
  }

  def printFont(name: String)(font: FIGfont): Unit =
    for (l <- 0 until font.header.height) {
      for (c <- name) print(font.characters(c).lines(l))
      print("\n")
    }
}

// 15 = 8 + 2 + 1
// Vector(FullWidthLayoutOldlayout, KerningLayoutOldlayout, HorizontalSmushingRule1Oldlayout, HorizontalSmushingRule2Oldlayout),
// 24463
// Vector(HorizontalSmushingRule1NewLayout, HorizontalSmushingRule2NewLayout, HorizontalSmushingRule3NewLayout, HorizontalSmushingRule4NewLayout, HorizontalSmushingNewLayout, VerticalSmushingRule1NewLayout, VerticalSmushingRule2NewLayout, VerticalSmushingRule3NewLayout, VerticalSmushingRule4NewLayout, VerticalSmushingRule5NewLayout, VerticalSmushingNewLayout)),
